import type { User } from '../auth.js'
import { layout } from '../dashboard.js'
import type { CrmStore } from './store.js'
import { ACTIVE_CRM_STAGES, CRM_STAGES, attributionLabel, stageLabel, type CrmStage, type FollowUp, type OpportunityView } from './types.js'

function esc(value: unknown): string {
  return String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;')
}

function money(valueMinor: number | null, currency: string | null): string {
  if (valueMinor === null || !currency) return 'Value not set'
  try { return new Intl.NumberFormat('en', { style: 'currency', currency }).format(valueMinor / 100) } catch { return `${(valueMinor / 100).toFixed(2)} ${currency}` }
}

function moneyGroups(groups: Record<string, number>): string {
  const entries = Object.entries(groups)
  return entries.length ? entries.map(([currency, value]) => money(value, currency)).join(' + ') : 'No recorded value'
}

function dateTime(value: string | null): string {
  if (!value) return 'Not set'
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? 'Unknown' : new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(date)
}

const CRM_STYLES = `<style>
  .crm-shell{max-width:1280px;margin:0 auto;padding:0 24px 80px}.crm-head{display:flex;align-items:end;justify-content:space-between;gap:24px;padding:38px 0 24px}.crm-head h1{margin:0;font:500 clamp(38px,5vw,60px)/.98 var(--display);letter-spacing:-.04em}.crm-head p{max-width:620px;margin:10px 0 0;color:var(--body)}
  .crm-nav{display:flex;gap:5px;margin-bottom:18px;padding:5px;width:max-content;max-width:100%;overflow:auto;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.72)}.crm-nav a{padding:9px 14px;border-radius:999px;text-decoration:none;color:var(--body);font-size:12px;font-weight:650;white-space:nowrap}.crm-nav a.active{background:#fff;color:var(--ink);box-shadow:0 1px 4px rgba(12,10,9,.09)}
  .metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.metric{padding:20px;border:1px solid var(--line);border-radius:18px;background:rgba(255,255,255,.88)}.metric-label{display:block;color:var(--muted);font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.07em}.metric-value{display:block;margin-top:8px;font:500 25px/1.05 var(--display)}.metric-help{display:block;margin-top:6px;color:var(--muted);font-size:10px}
  .crm-panel{min-width:0;padding:24px;border:1px solid var(--line);border-radius:20px;background:rgba(255,255,255,.9);box-shadow:0 8px 32px rgba(12,10,9,.045)}.panel-title{display:flex;align-items:start;justify-content:space-between;gap:18px;margin-bottom:18px}.panel-title h2{margin:0;font:500 29px/1 var(--display)}.panel-title p{margin:6px 0 0;color:var(--muted);font-size:12px}.crm-layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:18px}.crm-layout>*{min-width:0}.stack{display:grid;gap:18px}.board{display:grid;max-width:100%;grid-template-columns:repeat(5,minmax(155px,1fr));gap:10px;overflow-x:auto;padding:2px 2px 14px;scroll-snap-type:x proximity}.stage{min-height:280px;padding:12px;border:1px solid var(--line);border-radius:16px;background:rgba(245,245,245,.72);scroll-snap-align:start}.stage-head{display:flex;justify-content:space-between;gap:8px;margin-bottom:12px;font-size:12px;font-weight:700}.stage-count{color:var(--muted)}.deal{display:block;margin-top:9px;padding:12px;border:1px solid var(--line);border-radius:13px;background:#fff;text-decoration:none}.deal:hover{border-color:var(--line-strong);box-shadow:0 8px 18px rgba(12,10,9,.05)}.deal strong,.person-row strong{display:block;font-size:13px}.deal span,.person-row span{display:block;margin-top:3px;color:var(--muted);font-size:11px}.deal-value{margin-top:10px!important;color:var(--ink)!important;font-weight:700!important}
  .list{display:grid}.person-row,.follow-row,.activity-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;padding:15px 0;border-top:1px solid var(--line);text-decoration:none}.person-row:first-child,.follow-row:first-child,.activity-row:first-child{border-top:0}.activity-row strong{display:block}.activity-row>span>span{display:block;margin-top:3px;color:var(--muted);font-size:11px}.row-meta{text-align:right;color:var(--muted);font-size:11px}.follow-row{grid-template-columns:auto minmax(0,1fr) auto;align-items:center}.due-dot{width:9px;height:9px;border-radius:50%;background:var(--amber)}.due-dot.future{background:var(--green)}
  details.form-card{border:1px solid var(--line);border-radius:16px;background:#fff}details.form-card>summary{padding:16px;cursor:pointer;font-size:13px;font-weight:700;list-style:none}details.form-card>summary::-webkit-details-marker{display:none}details.form-card>summary::after{content:'+';float:right;font-size:18px;font-weight:400}details[open].form-card>summary::after{content:'−'}.crm-form{display:grid;gap:12px;padding:0 16px 16px}.field{display:grid;gap:5px}.field label{font-size:11px;font-weight:700}.field input,.field select,.field textarea{width:100%;min-height:44px;padding:10px 12px;border:1px solid var(--line-strong);border-radius:11px;background:#fff;color:var(--ink);font:inherit}.field textarea{min-height:90px;resize:vertical}.field small{color:var(--muted);font-size:10px}.field-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.check{display:flex;align-items:flex-start;gap:9px;color:var(--body);font-size:11px}.check input{margin-top:3px}.form-message{min-height:18px;margin:0;color:var(--red);font-size:11px}.form-message.ok{color:var(--green)}
  .empty{padding:28px;border:1px dashed var(--line-strong);border-radius:15px;background:rgba(245,245,245,.62);text-align:center}.empty h3{margin:0;font:500 23px/1.1 var(--display)}.empty p{margin:7px auto 0;max-width:440px;color:var(--muted);font-size:12px}.badge{display:inline-flex;padding:5px 9px;border-radius:999px;background:var(--green-soft);color:var(--green);font-size:10px;font-weight:700}.badge.unknown{background:var(--canvas);color:var(--muted)}.danger-note{padding:12px;border:1px solid #efdab0;border-radius:12px;background:var(--amber-soft);color:#6e5832;font-size:11px}.back{display:inline-block;margin-bottom:14px;color:var(--body);font-size:12px;font-weight:700;text-decoration:none}.truth{margin:14px 0 0;color:var(--muted);font-size:10px}.swipe-note{display:none;margin:-6px 0 10px;color:var(--muted);font-size:10px;font-weight:650}
  @media(max-width:899px){.crm-shell{padding:0 18px 90px}.crm-head{align-items:start;flex-direction:column}.metrics{grid-template-columns:1fr 1fr}.crm-layout{grid-template-columns:minmax(0,1fr)}.swipe-note{display:block}}
  @media(max-width:599px){.crm-shell{padding:0 12px 90px}.crm-head{padding:24px 6px 18px}.crm-head h1{font-size:42px}.metrics{grid-template-columns:1fr}.crm-panel{padding:19px;border-radius:18px}.panel-title{flex-direction:column}.panel-title form{width:100%}.field-row{grid-template-columns:1fr}.person-row,.activity-row{grid-template-columns:1fr}.row-meta{text-align:left}.crm-nav{width:100%;border-radius:15px}.crm-nav a{flex:1;text-align:center}.board{margin:0 -5px}.stage{min-width:82vw}}
</style>`

function shell(user: User, active: 'pipeline' | 'people' | 'followups', title: string, intro: string, body: string): string {
  const initials = (user.name ?? user.email ?? 'You').slice(0, 2).toUpperCase()
  return layout(title, `${CRM_STYLES}<a class="skip-link" href="#main">Skip to content</a><header class="topbar"><a class="brand" href="/dashboard"><img src="/onboarding/bizzclaw-mascot.png" alt=""/><span class="brand-name">BizzClaw</span></a><nav class="primary-nav" aria-label="Primary"><a class="nav-link" href="/dashboard">Home</a><a class="nav-link active" href="/dashboard/pipeline" aria-current="page">Customers</a><a class="nav-link" href="/dashboard/activity">Recent work</a></nav><span class="status ready"><span class="status-dot"></span><span>CRM ready</span></span><details class="user-menu"><summary><span class="user-chip">${esc(initials)}</span></summary><div class="menu-card"><div class="menu-identity"><strong>${esc(user.name ?? 'Account')}</strong><span>${esc(user.email ?? '')}</span></div><a href="/api/auth/sign-out?callbackURL=/login">Sign out</a></div></details></header><main class="crm-shell" id="main"><header class="crm-head"><div><p class="eyebrow">Customer relationships</p><h1>${esc(title)}</h1><p>${esc(intro)}</p></div><a class="btn btn-secondary" href="/dashboard">Back home</a></header><nav class="crm-nav" aria-label="CRM sections"><a class="${active === 'pipeline' ? 'active' : ''}" href="/dashboard/pipeline">Opportunities</a><a class="${active === 'people' ? 'active' : ''}" href="/dashboard/pipeline/people">People</a><a class="${active === 'followups' ? 'active' : ''}" href="/dashboard/pipeline/follow-ups">Follow-ups</a></nav>${body}</main>${FORM_SCRIPT}`)
}

function opportunityCard(item: OpportunityView): string {
  return `<a class="deal" href="/dashboard/pipeline/opportunities/${esc(item.id)}"><strong>${esc(item.title)}</strong><span>${esc(item.contactName)}${item.company ? ` · ${esc(item.company)}` : ''}</span><span class="deal-value">${esc(money(item.valueMinor, item.currency))}</span>${item.nextFollowUp ? `<span>Next: ${esc(item.nextFollowUp.action)}</span>` : ''}</a>`
}

function option(value: string, label: string, selected?: boolean): string { return `<option value="${esc(value)}"${selected ? ' selected' : ''}>${esc(label)}</option>` }

function form(endpoint: string, method: 'POST' | 'PATCH', fields: string, label: string): string {
  return `<form class="crm-form" data-api-form data-endpoint="${esc(endpoint)}" data-method="${method}">${fields}<p class="form-message" role="status"></p><button class="btn btn-primary" type="submit">${esc(label)}</button></form>`
}

function metrics(store: CrmStore): string {
  const summary = store.summary()
  return `<section class="metrics" aria-label="CRM summary"><article class="metric"><span class="metric-label">People</span><span class="metric-value">${summary.peopleCount}</span><span class="metric-help">Real CRM records</span></article><article class="metric"><span class="metric-label">Open opportunities</span><span class="metric-value">${summary.activeOpportunityCount}</span><span class="metric-help">${esc(moneyGroups(summary.activeValueByCurrency))}</span></article><article class="metric"><span class="metric-label">Follow-ups due</span><span class="metric-value">${summary.followUpsDue}</span><span class="metric-help">Pending actions due now</span></article><article class="metric"><span class="metric-label">Won this month</span><span class="metric-value">${esc(moneyGroups(summary.wonThisMonthByCurrency))}</span><span class="metric-help">Only opportunities explicitly marked Won</span></article></section>`
}

function renderPipeline(user: User, store: CrmStore): string {
  const opportunities = store.listOpportunities()
  const contacts = store.listContacts()
  const board = ACTIVE_CRM_STAGES.map((stage) => {
    const items = opportunities.filter((item) => item.stage === stage)
    return `<section class="stage" aria-labelledby="stage-${stage}"><div class="stage-head"><span id="stage-${stage}">${stageLabel(stage)}</span><span class="stage-count">${items.length}</span></div>${items.map(opportunityCard).join('') || '<p class="truth">No opportunities here yet.</p>'}</section>`
  }).join('')
  const contactOptions = contacts.map((person) => option(person.id, `${person.name}${person.company ? ` — ${person.company}` : ''}`)).join('')
  const add = contacts.length ? `<details class="form-card"><summary>Add opportunity</summary>${form('/api/crm/opportunities', 'POST', `<div class="field"><label for="person">Person</label><select id="person" name="contactId" required>${contactOptions}</select></div><div class="field"><label for="deal-title">Opportunity name</label><input id="deal-title" name="title" maxlength="200" required/></div><div class="field-row"><div class="field"><label for="deal-stage">Stage</label><select id="deal-stage" name="stage">${ACTIVE_CRM_STAGES.map((stage) => option(stage, stageLabel(stage))).join('')}</select></div><div class="field"><label for="deal-date">Expected close</label><input id="deal-date" name="expectedCloseAt" type="date"/></div></div><div class="field-row"><div class="field"><label for="deal-value">Value</label><input id="deal-value" name="valueMajor" inputmode="decimal" placeholder="0.00"/></div><div class="field"><label for="deal-currency">Currency</label><input id="deal-currency" name="currency" maxlength="3" placeholder="USD"/></div></div>`, 'Add opportunity')}</details>` : `<div class="empty"><h3>Add a person first</h3><p>An opportunity must belong to a real person. Start in People, then come back here.</p><a class="btn btn-secondary" href="/dashboard/pipeline/people">Add a person</a></div>`
  return shell(user, 'pipeline', 'Opportunities', 'Keep every real sales conversation moving, without invented pipeline or revenue numbers.', `${metrics(store)}<div class="crm-layout"><section class="crm-panel"><div class="panel-title"><div><h2>Active pipeline</h2><p>Move from first contact to proposal. Won and Lost require your explicit confirmation.</p></div></div><p class="swipe-note">Swipe to see every stage →</p><div class="board">${board}</div><p class="truth">Values are customer-entered records. BizzClaw never presents forecasts or influenced revenue as guaranteed income.</p></section><aside class="stack side">${add}<section class="crm-panel"><div class="panel-title"><div><h2>Closed outcomes</h2><p>Explicitly recorded business results.</p></div></div><div class="list">${opportunities.filter((item) => item.stage === 'won' || item.stage === 'lost').slice(0, 6).map(opportunityCard).join('') || '<div class="empty"><h3>No closed outcomes</h3><p>Nothing will appear here until you confirm Won or Lost.</p></div>'}</div></section></aside></div>`)
}

function renderPeople(user: User, store: CrmStore, search: string): string {
  const contacts = store.listContacts(search)
  const list = contacts.map((person) => `<a class="person-row" href="/dashboard/pipeline/people/${esc(person.id)}"><span><strong>${esc(person.name)}</strong><span>${esc(person.company ?? 'No company')} · ${person.relationship === 'customer' ? 'Customer' : 'Lead'}</span></span><span class="row-meta">${person.openOpportunityCount} open<br/>${esc(money(person.openOpportunityValueMinor, person.openOpportunityCurrency))}</span></a>`).join('')
  const addFields = `<div class="field"><label for="name">Name</label><input id="name" name="name" maxlength="160" autocomplete="name" required/></div><div class="field"><label for="company">Company</label><input id="company" name="company" maxlength="160" autocomplete="organization"/></div><div class="field-row"><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email"/></div><div class="field"><label for="phone">Phone</label><input id="phone" name="phone" type="tel" autocomplete="tel"/></div></div><div class="field-row"><div class="field"><label for="relationship">Relationship</label><select id="relationship" name="relationship">${option('lead', 'Lead')}${option('customer', 'Customer')}</select></div><div class="field"><label for="consent">Contact permission</label><select id="consent" name="consent">${option('unknown', 'Not recorded')}${option('granted', 'Granted')}${option('denied', 'Do not contact')}</select></div></div>`
  return shell(user, 'people', 'People', 'A private, practical list of leads and customers. Contact details are encrypted at rest.', `<div class="crm-layout"><section class="crm-panel"><div class="panel-title"><div><h2>${search ? `Results for “${esc(search)}”` : 'All people'}</h2><p>${contacts.length} real record${contacts.length === 1 ? '' : 's'}.</p></div><form method="get"><label class="field"><span class="sr-only">Search people</span><input name="search" value="${esc(search)}" placeholder="Search name or company"/></label></form></div><div class="list">${list || '<div class="empty"><h3>No people found</h3><p>Add the first person or change your search.</p></div>'}</div></section><aside class="side"><details class="form-card" open><summary>Add person</summary>${form('/api/crm/contacts', 'POST', addFields, 'Add person')}</details></aside></div>`)
}

function followRow(item: FollowUp, store: CrmStore): string {
  const person = store.getContact(item.contactId)
  const due = Date.parse(item.dueAt) <= Date.now()
  return `<article class="follow-row"><span class="due-dot ${due ? '' : 'future'}" aria-hidden="true"></span><span><strong>${esc(item.action)}</strong><span>${esc(person?.name ?? 'Person')} · ${esc(dateTime(item.dueAt))}</span></span><form data-api-form data-endpoint="/api/crm/follow-ups/${esc(item.id)}/complete" data-method="POST"><p class="form-message" role="status"></p><button class="btn btn-secondary" type="submit">Done</button></form></article>`
}

function renderFollowUps(user: User, store: CrmStore): string {
  const followUps = store.listFollowUps()
  const contacts = store.listContacts()
  const add = contacts.length ? `<details class="form-card" open><summary>Add follow-up</summary>${form('/api/crm/follow-ups', 'POST', `<div class="field"><label for="follow-person">Person</label><select id="follow-person" name="contactId">${contacts.map((person) => option(person.id, person.name)).join('')}</select></div><div class="field"><label for="follow-action">Next action</label><input id="follow-action" name="action" maxlength="500" required placeholder="Call about the proposal"/></div><div class="field"><label for="follow-date">When</label><input id="follow-date" name="dueAt" type="datetime-local" required/></div>`, 'Add follow-up')}</details>` : '<div class="empty"><h3>Add a person first</h3><p>Follow-ups must belong to a real person.</p></div>'
  return shell(user, 'followups', 'Follow-ups', 'A focused list of the next conversations that need your attention.', `<div class="crm-layout"><section class="crm-panel"><div class="panel-title"><div><h2>What’s next</h2><p>Due items appear first. Completing one keeps its history.</p></div></div><div class="list">${followUps.map((item) => followRow(item, store)).join('') || '<div class="empty"><h3>Nothing due</h3><p>Add the next useful action when a customer conversation needs a clear owner and date.</p></div>'}</div></section><aside class="side">${add}</aside></div>`)
}

function renderOpportunity(user: User, store: CrmStore, id: string): string {
  const item = store.listOpportunities().find((candidate) => candidate.id === id)
  if (!item) return shell(user, 'pipeline', 'Opportunity not found', 'This record does not exist in your workspace.', '<a class="btn btn-secondary" href="/dashboard/pipeline">Back to opportunities</a>')
  const activities = store.listActivities({ opportunityId: id })
  const stageForm = form(`/api/crm/opportunities/${id}`, 'PATCH', `<div class="field"><label for="stage">Stage</label><select id="stage" name="stage">${CRM_STAGES.map((stage) => option(stage, stageLabel(stage), stage === item.stage)).join('')}</select><small>Won and Lost are confirmed business outcomes.</small></div><div class="field"><label for="loss">Loss reason</label><input id="loss" name="lossReason" maxlength="500" value="${esc(item.lossReason ?? '')}"/></div><label class="check"><input type="checkbox" name="confirmed" value="true"/> I confirm this outcome if I select Won or Lost.</label>`, 'Update stage')
  const valueForm = form(`/api/crm/opportunities/${id}`, 'PATCH', `<div class="field-row"><div class="field"><label for="value">Value</label><input id="value" name="valueMajor" inputmode="decimal" value="${item.valueMinor === null ? '' : (item.valueMinor / 100).toFixed(2)}"/></div><div class="field"><label for="currency">Currency</label><input id="currency" name="currency" maxlength="3" value="${esc(item.currency ?? '')}"/></div></div><label class="check"><input type="checkbox" name="confirmed" value="true" required/> I confirm this monetary value is accurate.</label>`, 'Update value')
  const noteForm = form(`/api/crm/opportunities/${id}/notes`, 'POST', '<div class="field"><label for="note">Add context</label><textarea id="note" name="summary" maxlength="2000" required></textarea></div>', 'Add note')
  return shell(user, 'pipeline', item.title, `${item.contactName}${item.company ? ` at ${item.company}` : ''}`, `<a class="back" href="/dashboard/pipeline">← All opportunities</a><div class="metrics"><article class="metric"><span class="metric-label">Stage</span><span class="metric-value">${esc(stageLabel(item.stage))}</span></article><article class="metric"><span class="metric-label">Value</span><span class="metric-value">${esc(money(item.valueMinor, item.currency))}</span></article><article class="metric"><span class="metric-label">Expected close</span><span class="metric-value">${esc(item.expectedCloseAt ? dateTime(item.expectedCloseAt) : 'Not set')}</span></article><article class="metric"><span class="metric-label">Revenue source</span><span class="metric-value">${esc(attributionLabel(item.attributionState))}</span><span class="metric-help">${esc(item.attributionEvidence ?? 'No supporting evidence recorded')}</span></article></div><div class="crm-layout"><section class="crm-panel"><div class="panel-title"><div><h2>History</h2><p>An immutable record of real changes and notes.</p></div></div><div class="list">${activities.map((activity) => `<article class="activity-row"><span><strong>${esc(activity.summary)}</strong><span>${esc(activity.actor === 'bizzclaw' ? 'BizzClaw' : activity.actor === 'customer' ? 'You' : activity.actor)}</span></span><span class="row-meta">${esc(dateTime(activity.createdAt))}</span></article>`).join('')}</div></section><aside class="stack side"><details class="form-card" open><summary>Move stage</summary>${stageForm}</details><details class="form-card"><summary>Set value</summary>${valueForm}</details><details class="form-card"><summary>Add note</summary>${noteForm}</details><p class="danger-note">BizzClaw records “verified source” only with concrete evidence. “Influenced” never means guaranteed or solely caused revenue.</p></aside></div>`)
}

function renderPerson(user: User, store: CrmStore, id: string): string {
  const person = store.getContact(id)
  if (!person) return shell(user, 'people', 'Person not found', 'This record does not exist in your workspace.', '<a class="btn btn-secondary" href="/dashboard/pipeline/people">Back to people</a>')
  const opportunities = store.listOpportunities().filter((item) => item.contactId === id)
  const fields = `<div class="field"><label for="name">Name</label><input id="name" name="name" maxlength="160" value="${esc(person.name)}" required/></div><div class="field"><label for="company">Company</label><input id="company" name="company" maxlength="160" value="${esc(person.company ?? '')}"/></div><div class="field-row"><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" value="${esc(person.email ?? '')}"/></div><div class="field"><label for="phone">Phone</label><input id="phone" name="phone" type="tel" value="${esc(person.phone ?? '')}"/></div></div><div class="field-row"><div class="field"><label for="relationship">Relationship</label><select id="relationship" name="relationship">${option('lead', 'Lead', person.relationship === 'lead')}${option('customer', 'Customer', person.relationship === 'customer')}</select></div><div class="field"><label for="consent">Contact permission</label><select id="consent" name="consent">${option('unknown', 'Not recorded', person.consent === 'unknown')}${option('granted', 'Granted', person.consent === 'granted')}${option('denied', 'Do not contact', person.consent === 'denied')}</select></div></div>`
  return shell(user, 'people', person.name, person.company ?? (person.relationship === 'customer' ? 'Customer' : 'Lead'), `<a class="back" href="/dashboard/pipeline/people">← All people</a><div class="crm-layout"><section class="crm-panel"><div class="panel-title"><div><h2>Opportunities</h2><p>Sales conversations connected to this person.</p></div></div><div class="list">${opportunities.map(opportunityCard).join('') || '<div class="empty"><h3>No opportunities yet</h3><p>Create one from the Opportunities page when there is a real sales conversation.</p></div>'}</div></section><aside class="side"><details class="form-card" open><summary>Edit person</summary>${form(`/api/crm/contacts/${id}`, 'PATCH', fields, 'Save changes')}</details></aside></div>`)
}

const FORM_SCRIPT = `<script>
  document.addEventListener('submit',async(event)=>{const form=event.target.closest('[data-api-form]');if(!form)return;event.preventDefault();const button=form.querySelector('button[type=submit]');const message=form.querySelector('.form-message');button.disabled=true;message.textContent='Saving…';message.classList.remove('ok');const data={};for(const [key,value] of new FormData(form)){const field=form.elements.namedItem(key);if(key==='confirmed')data[key]=true;else if(field&&field.type==='datetime-local'&&value)data[key]=new Date(value).toISOString();else data[key]=value}try{const response=await fetch(form.dataset.endpoint,{method:form.dataset.method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save');message.textContent='Saved';message.classList.add('ok');setTimeout(()=>location.reload(),250)}catch(error){message.textContent=error.message||'Could not save';button.disabled=false}})
</script>`

export function renderCrmPage(user: User, store: CrmStore, url: URL): string {
  const opportunity = url.pathname.match(/^\/dashboard\/pipeline\/opportunities\/([^/]+)$/)
  if (opportunity) return renderOpportunity(user, store, opportunity[1]!)
  const person = url.pathname.match(/^\/dashboard\/pipeline\/people\/([^/]+)$/)
  if (person) return renderPerson(user, store, person[1]!)
  if (url.pathname === '/dashboard/pipeline/people') return renderPeople(user, store, url.searchParams.get('search') ?? '')
  if (url.pathname === '/dashboard/pipeline/follow-ups') return renderFollowUps(user, store)
  return renderPipeline(user, store)
}
